### ISSUE TITLE
Update FactoryGirl to FactoryBot

### ISSUE THREAD

**Issue by RSid** [MassBailFund/MassBailFund#62]
https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md

**Comment by AlexRiina** [comment]
I think this is resolved in https://github.com/MassBailFund/MassBailFund/pull/65/commits/f7210edaab9abae2bef0fd4368efcbd6551429ab

**Comment by RSid** [comment]
resolved in #65

**Comment by RSid** [comment]
Resolved in #65
